services:
    postgres:
        container_name: pass_in_db
        image: postgres
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_USER}
            POSTGRES_DB: pass_in_db

        ports:
            - "5432:5432"
